### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by fmvilas** [stephenplusplus/byestyle#1]
Hi

Have you considered implementing the feature of grouping each console.warn output? i.e. you could use console.group when available and a function that prints "-----" when not.

I think it could be interesting. I'm sorry I don't have too much time to make a pull request.

Hope it helps!

**Comment by stephenplusplus** [comment]
Great idea! Here's what it looks like now:

![](https://raw.githubusercontent.com/stephenplusplus/byestyle/master/example.png)

**Comment by fmvilas** [comment]
Nice! Glad it helped you!
